ln -s Dropbox/dotfiles/mac/.bash_profile .bash_profile
ln -s Dropbox/dotfiles/mac/.bashrc .bashrc
ln -s Dropbox/dotfiles/common/.gitconfig .gitconfig
ln -s Dropbox/dotfiles/common/.sbtconfig .sbtconfig
ln -s Dropbox/dotfiles/common/.ssh .ssh
ln -s Dropbox/dotfiles/common/.tmux.conf .tmux.conf
ln -s Dropbox/dotfiles/common/.vim .vim
ln -s Dropbox/dotfiles/common/.vimperator .vimperator
ln -s Dropbox/dotfiles/common/.vimperatorrc .vimperatorrc
ln -s Dropbox/dotfiles/mac/.vimrc .vimrc
ln -s Dropbox/dotfiles/common/git-completion.bash git-completion.bash
